- name: homebrew update
  homebrew:
    update_homebrew: true

- name: homebrew tap
  homebrew_tap:
    name: '{{ homebrew_taps }}'
    state: present

- name: homebrew packages insatall
  homebrew:
    name: '{{ homebrew_packages }}'
    state: present
    update_homebrew: true
    upgrade_all: true

- name: homebrew cask packages install
  community.general.homebrew_cask:
    name: '{{ homebrew_cask_packages }}'
    state: present
    install_options: 'appdir=/Applications'
