- name: homebrew update
  homebrew:
    update_homebrew: true

- name: homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_taps }}'

- name: homebrew packages insatall
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'

- name: homebrew cask packages install
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: present
    install_options: 'appdir=/Applications'
  with_items: '{{ homebrew_cask_packages }}'
